version: "3.7"

services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        command: python ./manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/usr/src/partiguiden-backend
        ports:
            - 8000:8000
        depends_on:
            - db
        env_file:
            - ./.env.dev
    db:
        build:
            context: .
            dockerfile: Dockerfile.db
        volumes:
            - ./.postgres-data:/var/lib/postgresql/data
        env_file:
            - ./.env.dev
