version: "3.7"

services:
  web:
    build: .
    command: pipenv run ./manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/partiguiden-backend
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - ./.env.dev
  db:
    image: postgres:12.2-alpine
    env_file:
      - ./.env.dev
