[tool.black]
line-length = 120
exclude = "/*migrations/*/"

[tool.isort]
line_length = 120
skip="migrations"
profile="black"

[tool.mypy]
files = "partiguiden,standpoints"
ignore_missing_imports = true
