# Generated by Django 3.1.5 on 2021-03-06 18:48

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Party",
            fields=[
                (
                    "id",
                    models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name="Partiförkortning"),
                ),
                ("name", models.CharField(max_length=50, unique=True, verbose_name="Partinamn")),
            ],
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, unique=True, verbose_name="Sakområde")),
                (
                    "related_subject",
                    models.ManyToManyField(
                        blank=True,
                        related_name="_subject_related_subject_+",
                        to="standpoints.Subject",
                        verbose_name="Relaterade sakområden",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Standpoint",
            fields=[
                ("id", models.CharField(max_length=64, primary_key=True, serialize=False)),
                ("link", models.CharField(max_length=100, unique=True, verbose_name="Länk")),
                ("title", models.CharField(default="Titel", max_length=50, verbose_name="Ståndpunkt")),
                (
                    "content",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200), size=None, verbose_name="Åsikt"
                    ),
                ),
                ("date", models.DateField(auto_now_add=True, null=True, verbose_name="datum")),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="standpoints.party", verbose_name="Parti"
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="standpoints.subject",
                        verbose_name="Sakområde",
                    ),
                ),
            ],
        ),
    ]
