# Generated by Django 3.1.7 on 2021-03-06 22:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standpoints', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standpoint',
            name='content',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), size=None, verbose_name='Åsikt'),
        ),
        migrations.AlterField(
            model_name='standpoint',
            name='title',
            field=models.CharField(default='Titel', max_length=100, verbose_name='Ståndpunkt'),
        ),
    ]
