# Generated by Django 3.1.5 on 2021-01-04 20:40

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standpoints', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standpoint',
            name='link',
            field=models.CharField(max_length=100, serialize=False, unique=True, verbose_name='Länk'),
        ),
        migrations.AlterField(
            model_name='standpoint',
            name='content',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None, verbose_name='Åsikt'),
        ),
        migrations.AlterField(
            model_name='standpoint',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='standpoints.subject', verbose_name='Sakområde'),
        ),
        migrations.RemoveField(
            model_name='party',
            name='id',
        ),
        migrations.AlterField(
            model_name='party',
            name='abbreviation',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='Partiförkortning'),
        ),
        migrations.AlterField(
            model_name='party',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Partinamn'),
        ),
        migrations.AlterField(
            model_name='standpoint',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='standpoint',
            name='link',
            field=models.CharField(max_length=100, unique=True, verbose_name='Länk'),
        ),
        migrations.AlterField(
            model_name='standpoint',
            name='id',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
