# Generated by Django 3.0.4 on 2020-03-10 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standpoints', '0001_squashed_0005_auto_20200309_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='date',
        ),
        migrations.AddField(
            model_name='standpoint',
            name='date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='datum'),
        ),
    ]
