# Generated by Django 3.2.4 on 2021-06-25 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("standpoints", "0001_alter_standpoint_subject"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="party",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="standpoint",
            options={"ordering": ["party", "title"]},
        ),
        migrations.AlterModelOptions(
            name="subject",
            options={"ordering": ["name"]},
        ),
    ]
