# Generated by Django 3.0.4 on 2020-03-10 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standpoints', '0002_auto_20200310_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='standpoint',
            name='link',
            field=models.CharField(blank=True, max_length=100, verbose_name='Länk'),
        ),
    ]
