# Generated by Django 3.2.4 on 2021-06-25 20:14

from django.db import migrations, models

from standpoints.constants import DB_COLLATION


class Migration(migrations.Migration):

    dependencies = [
        ("standpoints", "0002_auto_20210625_1956"),
    ]

    operations = [
        migrations.RunSQL("CREATE COLLATION {} (locale = '{}.utf8')".format(DB_COLLATION, DB_COLLATION)),
        migrations.AlterField(
            model_name="party",
            name="name",
            field=models.CharField(db_collation="sv_SE", max_length=50, unique=True, verbose_name="Partinamn"),
        ),
        migrations.AlterField(
            model_name="standpoint",
            name="title",
            field=models.CharField(db_collation="sv_SE", default="Titel", max_length=100, verbose_name="Ståndpunkt"),
        ),
        migrations.AlterField(
            model_name="subject",
            name="name",
            field=models.CharField(db_collation="sv_SE", max_length=50, unique=True, verbose_name="Sakområde"),
        ),
    ]
