# Generated by Django 3.0.4 on 2020-03-10 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standpoints', '0003_standpoint_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standpoint',
            name='link',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Länk'),
        ),
    ]
