# Generated by Django 3.2.4 on 2021-06-26 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("standpoints", "0003_auto_20210625_2014"),
    ]

    operations = [
        migrations.RenameField(model_name="subject", old_name="related_subject", new_name="related_subjects"),
    ]
