# Generated by Django 3.0.4 on 2020-03-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standpoints', '0004_auto_20200310_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standpoint',
            name='link',
            field=models.CharField(max_length=100, unique=True, verbose_name='Länk'),
        ),
    ]
