# Generated by Django 4.0.2 on 2022-02-26 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("standpoints", "0004_auto_20210626_1137"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="related_subjects",
            field=models.ManyToManyField(blank=True, to="standpoints.Subject", verbose_name="Relaterade sakområden"),
        ),
    ]
