# Generated by Django 4.0.5 on 2022-06-17 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standpoints', '0005_alter_subject_related_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standpoint',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='datum'),
        ),
    ]
