# Generated by Django 4.0.5 on 2022-06-26 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standpoints', '0006_alter_standpoint_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standpoint',
            name='id',
        ),
        migrations.AlterField(
            model_name='standpoint',
            name='link',
            field=models.CharField(max_length=150, primary_key=True, serialize=False, unique=True, verbose_name='Länk'),
        ),
    ]
