name: CI Workflow

on: [push]

jobs:
    check:
        name: Check
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v3
            - name: Use Python 3.9
              uses: actions/setup-python@v4
              with:
                  python-version: 3.9
            - name: Install pipenv
              run: pip install pipenv
            - name: Install PIP dependencies
              run: pipenv install --dev
            - name: Lint with Flake8
              run: pipenv run lint
              if: always()
            - name: Lint with Black
              run: pipenv run format --check
              if: always()
            - name: Import sort with isort
              run: pipenv run import-sort --check
              if: always()
            - name: Type check with mypy
              run: pipenv run mypy
              if: always()
