name: CI

on: [push]

jobs:
  check:
    name: Check
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Use Python 3.11.0
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.0"
      - name: Install PIP dependencies
        run: pip install -r requirements-dev.txt
      - name: Lint check
        run: make lint
        if: always()
      - name: Format check
        run: make format-check
        if: always()
